# Generated by Django 5.1.3 on 2024-11-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0002_alter_customuser_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="skill",
            field=models.CharField(default=" Required skills", max_length=100),
        ),
    ]
