# Generated by Django 5.1.3 on 2025-01-16 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0003_job_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="apply_before",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="ddate_of_posting",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="job",
            name="duration",
            field=models.CharField(default="Not mentioned", max_length=50),
        ),
        migrations.AddField(
            model_name="job",
            name="no_of_applicants",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
