# Generated by Django 5.1.3 on 2025-01-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0004_job_apply_before_job_ddate_of_posting_job_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(default=" Required experience", max_length=100),
        ),
    ]
